### ISSUE TITLE
项目太棒了！

### ISSUE THREAD

**Issue by xiaoleGun** [imsyy/home#1]
找了很久才发现这么宝藏的主页，太符合我审美了。不足之处在于你的commit然后就是移动端优化，希望移动端排版可以舒服一点，高斯模糊也加上。感谢感谢

**Comment by imsyy** [comment]
感谢支持 🤪
移动端确实有些问题，有空了我再搞搞
ps. 移动端是有高斯模糊的呀，另外我主页的名称字体是压缩过的，要是用了我名称以外的字母会变回默认字体，这里是 [完整字体](https://cdn.jsdelivr.net/gh/imsyy/file/font/Pacifico-Regular.ttf)
