### ISSUE TITLE
今年已度过月数似乎有误

### ISSUE THREAD

**Issue by Jerry-FaGe** [imsyy/home#101]
![image](https://user-images.githubusercontent.com/40235071/224071938-f23c581a-20bf-40e5-9b3f-2dc682069cf7.png)

如图，截图时间 `2023-03-09 23:28` 感觉应该是3月，不知道是我跟您对 `已度过月数` 的理解不同还是单纯写错了。。。下面的 `yearPass` 也是表示的3月

**Comment by imsyy** [comment]
确实写错了。不过感觉还是已经度过了2个月好一点，我把进度条也改成2个月的吧 😂

**Comment by Jerry-FaGe** [comment]
> 确实写错了。不过感觉还是已经度过了2个月好一点，我把进度条也改成2个月的吧 😂

那要照这么理解的话岂不是上面的三项也要同步 - 1 ，这样的话感觉会给人很强的违和感（虽然感觉也没什么人会仔细看这个模块吧 😂）

**Comment by imsyy** [comment]
> > 确实写错了。不过感觉还是已经度过了2个月好一点，我把进度条也改成2个月的吧 😂
> 
> 那要照这么理解的话岂不是上面的三项也要同步 - 1 ，这样的话感觉会给人很强的违和感（虽然感觉也没什么人会仔细看这个模块吧 😂）

确实，我再想想吧（说不定会把这个去掉呢 🤣）
