### ISSUE TITLE
怎么部署到自己宝塔面板

### ISSUE THREAD

**Issue by xccado** [imsyy/home#115]

**Comment by xsidc** [comment]
使用宝塔的Node项目创建，但是还是打不开页面，3000端口也没开

**Comment by imsyy** [comment]
> 使用宝塔的Node项目创建，但是还是打不开页面，3000端口也没开

https://github.com/imsyy/home/discussions/104

**Comment by loohalh** [comment]
我也是正常编译后传到网站根目录 3000端口未监听，你解决了没
