### ISSUE TITLE
高德API_KEY缺少安全密钥jscode，导致天气获取失败？

### ISSUE THREAD

**Issue by MitsumuneWeb3** [imsyy/home#123]
根据文档，我已经在.env文件中的VITE_WEATHER_KEY填入了自己申请的高德API Key（图一）。
但是在页面上运行时，出现了天气获取失败的错误提示信息（图二）。
然后，我在高德地图API的官方文档，发现自2021年12月02日后申请的API Key必须配备安全密钥jscode才能使用（图三）。
但是，我并未找到填写安全密钥jscode的位置。因此，不确定这个原因是否导致了天气获取失败？
![image](https://user-images.githubusercontent.com/59498164/232288127-51d21d0d-ef9d-416b-9d6c-a2ee117172a1.png)
![image](https://user-images.githubusercontent.com/59498164/232287750-17d9095b-8123-4012-881e-02da9f5df9c2.png)
![image](https://user-images.githubusercontent.com/59498164/232288375-08dd765c-3f71-4d94-ac7b-905d95b3b6fe.png)

**Comment by imsyy** [comment]
申请 `Web服务` 类型，不是 `Web端(JS API)`

**Comment by MitsumuneWeb3** [comment]
> 申请`Web服务`类型，不是`Web端(JS API)`

原来是我申请错了，重新申请了个就行了，感谢大佬(＞＜)
