### ISSUE TITLE
几个问题反馈

### ISSUE THREAD

**Issue by Atlantis829** [imsyy/home#140]
这个网站模板确实不错，一下是我在使用的时候遇到的一些问题，下面给出反馈。
1.这个网站在支持三级域名的显示的时候不完全，比如我的https://alx962.eu.org只显示alx962.eu而没有.org
2.这个网站在编译后存在路径问题，在不修改任何文件的情况下编译出来的index.htlm代码中存在路径问题，字体的路径也有问题，需要手动在/前面加上.
3.对于高德地图的key，现在申请的key必须配合密钥使用，希望指明key的密钥填写在哪里。

**Comment by imsyy** [comment]
感谢提供 😍 关于第三点，请参考：#123

**Comment by Atlantis829** [comment]
> 感谢提供 😍 关于第三点，请参考：#123
好的，感谢你的这么优秀的开源项目，你费心了
