### ISSUE TITLE
怎么不让路由后面写什么都跳转到主页

### ISSUE THREAD

**Issue by miloce** [imsyy/home#142]
怎么不让路由后面写什么都跳转到主页，想做一个单页模板跳转到同域名其他路径

**Comment by first19326** [comment]
这个问题，我也遇到了，这个是因为插件 `vite-plugin-html` 的问题，参见 [#102](https://github.com/vbenjs/vite-plugin-html/issues/102)，希望可以解决你的问题。

**Comment by first19326** [comment]
你好，你需要参照 [#102](https://github.com/vbenjs/vite-plugin-html/issues/102) 中的红框中的代码自行匹配不进行主页跳转的路径。例如："xxx/xxx/abc"，你需要 
```javascript 
if (excludeBaseUrl.indexOf("xxx/xxx/abc")) { return excludeBaseUrl; } 
```
你可以使用其他的 `javascript` 代码去匹配你的 `url`，可以是正则，总之匹配到了直接返回即可。
 [#102](https://github.com/vbenjs/vite-plugin-html/issues/102) 中的代码只是匹配 `static` 开头的 `url`。
希望可以解决你的问题。如果后续 `vite-plugin-html` 插件修改了这个 issue，那么更新插件就可以解决这个问题。
