### ISSUE TITLE
底部显示的设定bug

### ISSUE THREAD

**Issue by love88520** [imsyy/home#155]
### 问题描述

网页底下的TCP  可以修改了
网站底下的无名  不能跟随设置更换。
网站底下点击无名 的网页链接也没有更改成设置的网站。

**Comment by imsyy** [comment]
已修复

**Comment by love88520** [comment]
底部无名点击的链接现在变成（127.0.0.1/设置的域名）   这样的链接是打不开的呀？
直接跳到 index.html 不就好了，不管你访问的什么网页都是主页？
