### ISSUE TITLE
天气接口建议

### ISSUE THREAD

**Issue by echo-bytes** [imsyy/home#162]
### 问题描述

您好我是教书先生api免费接口的站长（https://api.oioweb.cn），近几日通过访问来源看到好几个搭建咱这个开源项目的主页，调用了 https://api.oioweb.cn/doc/weather/GetWeather 天气接口，我看咱这边项目是推荐的高德，配置还需要时间，所以自荐我这边的接口，还请采纳，最后感谢作者支持开源~ 开发出那么多好的开源项目

**Comment by imsyy** [comment]
感谢大佬支持，那我做下适配吧 🫡

**Comment by imsyy** [comment]
对了，每日调用有上限吗

**Comment by echo-bytes** [comment]
> 所有接口不限频次，无上限

**Comment by imsyy** [comment]
好的
