### ISSUE TITLE
小歪图片API接口更换

### ISSUE THREAD

**Issue by AdingApkgg** [imsyy/home#163]
小歪的随机图片API更换了，
从https://api.ixiaowai.cn/
换成https://api.aixiaowai.cn/

**Comment by imsyy** [comment]
感谢提醒

**Comment by Remtg** [comment]
已经打不开了

**Comment by AdingApkgg** [comment]
> 已经打不开了

这人好像跑路了，看看这个..

https://loliapi.com/
