### ISSUE TITLE
regular.min.css报错

### ISSUE THREAD

**Issue by Einstein-schrodinger** [imsyy/home#165]
### 站点链接

https://home.sqwdream.cloud/

### 问题描述

1.控制台出现如下报错，请问regular.min.css这个文件是在什么地方引入的？

### 补充信息

![image](https://github.com/imsyy/home/assets/62790820/2592e728-2bdb-4228-a2c0-9d56bb0ca160)

**Comment by imsyy** [comment]
字体文件，我开了防盗链，把这里换成上一行注释的内容就行了

https://github.com/imsyy/home/blob/9d2290d694a851e62461b90d6ca57071f6346f83/index.html#L21

**Comment by Einstein-schrodinger** [comment]
**谢谢大佬！**

**Comment by imsyy** [comment]
😘
