### ISSUE TITLE
新版本显示不完全

### ISSUE THREAD

**Issue by love88520** [imsyy/home#166]
### 站点链接

www.128my.com

### 问题描述

作者的新版本edge底部显示不完整

### 补充信息

![Screenshot_20230704_181516_com microsoft emmx](https://github.com/imsyy/home/assets/136620975/84e6996d-7395-4957-a91b-6f8598310db4)
![Screenshot_20230704_181547_com microsoft emmx](https://github.com/imsyy/home/assets/136620975/ee62881b-fed9-4a7a-be74-a0817cd92272)
早期版本与最新的作者主页对比，作者主页底部显示不完全

**Comment by love88520** [comment]
浏览器使用的微软edge浏览器。

**Comment by imsyy** [comment]
#81
