### ISSUE TITLE
建议在底部增加公安备案号

### ISSUE THREAD

**Issue by zjl12321** [imsyy/home#167]
### 问题描述

部分地区还要求公安备案，希望能在底部展示公安备案号
![image](https://github.com/imsyy/home/assets/13899649/cddb4cf6-8621-4ae2-88ad-3d88fe7f33d4)
这个是公安备案给的备案编号图标 ![备案图标](https://github.com/imsyy/home/assets/13899649/c331eb0e-6e07-4c31-b45c-b9ab8124412d)
还需要点击备案号能跳转到http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=“你的公安备案号" 这个链接

**Comment by imsyy** [comment]
暂时不考虑，可以自行添加
