### ISSUE TITLE
时光胶囊显示的今日度过小时出现问题

### ISSUE THREAD

**Issue by lan1oc** [imsyy/home#170]
### 站点链接

暂时没上传到服务器上

### 问题描述

显示为NaN

### 补充信息

看代码感觉是没啥问题，但如下图所示位置确实异常
![image](https://github.com/imsyy/home/assets/110882196/5b8a4c0a-88c0-4bc8-897a-5b33030df883)

**Comment by nova1751** [comment]
请提供详细的复现情况与案例

**Comment by lan1oc** [comment]
额，好像是浏览器的问题，再谷歌里看是
![A](https://github.com/imsyy/home/assets/110882196/9091ca79-fb18-4aba-bf0c-a18aed7da74c)
在edge上看就是
![Uploading B.png…]()

**Comment by nova1751** [comment]
有网站链接吗，可能是浏览器缓存的问题？尝试用无痕模式浏览一下看看？

**Comment by lan1oc** [comment]
网址：lan1oc.co，试了无痕，谷歌浏览器里查看是正常，在edge里时间就是负的

**Comment by nova1751** [comment]
> 网址：lan1oc.co，试了无痕，谷歌浏览器里查看是正常，在edge里时间就是负的

我这边谷歌浏览器和edge浏览器显示均正常，可以尝试在windows的应用程序和管理中对edge浏览器尝试进行修复，或者在edge浏览器中重置设置然后进行查看。

**Comment by lan1oc** [comment]
okok
