### ISSUE TITLE
这里的字体该怎么改呀

### ISSUE THREAD

**Issue by Kangnakamuyii** [imsyy/home#179]
### 问题描述

fork 项目之后，我把 imsyy.top 改成了自己的 neko.best，出现了字体上的错误，请问这块怎么改？

![图片](https://github.com/imsyy/home/assets/47733293/c5ecb330-f0ff-4451-a901-181a7ac05a76)

**Comment by imsyy** [comment]
请看说明文件

**Comment by shmilyabyy** [comment]
![image](https://github.com/imsyy/home/assets/77541484/4205930a-283b-44c6-8d8e-527c28d5cf18)
是这个吗？请问字体引入链接在哪里，实在是没找到，十分抱歉。

**Comment by ZipCz** [comment]
> ![image](https://private-user-images.githubusercontent.com/77541484/331060849-4205930a-283b-44c6-8d8e-527c28d5cf18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjMyOTksIm5iZiI6MTcxNTg2Mjk5OSwicGF0aCI6Ii83NzU0MTQ4NC8zMzEwNjA4NDktNDIwNTkzMGEtMjgzYi00NGM2LThkOGUtNTI3YzI4ZDVjZjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEyMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MzNkYmNlMzdlZjE4M2ZiNWVkZmQ0YTg5MzFmY2RkY2I4M2VkNzAyYjE2OGIwMDRlYzRlZTRmMWIwYmM4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SyInh2KjPoFLABurXU2bnGmW5JuSV8gRdg_XJtdM_Og) 是这个吗？请问字体引入链接在哪里，实在是没找到，十分抱歉。

一、在 控制台 安装字蛛（font-spider）（需要安装nodejs）
npm install font-spider -g

二、新建文件
在你的电脑中新建一个文件夹，在文件夹中新建两个文件第一个1.html，第二个font.css。
（一）新建1.html开始
<html>
<head>
  <link rel="stylesheet" href="font.css">
</head>
<body>
  
  <p class="ttf">16a4cnOopswWcdeirstvyHSW</p>
</body>
</html>
新建1.html结束


（二）新建 font.css 开始
@font-face {
  font-family: 'sf-pro-text_regular';
  /* src引入需要精简的ttf字体文件 */
  src: url('./Pacifico-Regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
body {
  font-family: "sf-pro-text_regular";
}
.ttf {
  font-family: 'sf-pro-text_regular';
}
新建 font.css 结束

三、修改文件内容
  1. 修改 src 引入需要精简的ttf字体文件名
 例：src: url('./Pacifico-Regular.ttf') format('truetype');

  2.直接将Pacifico-Regular.ttf放入根目录即可

  3.修改1.html 中要保留的文字
  <p class="ttf">16a4cnOopswWcdeirstvyHSW（这里就是需要保留的文字）</p>

四、在控制台 执行字蛛
font-spider 1.html

五、其他说明
特别注意：根目录 .font-spider 为原始备份文件
1. imsyy主页项目，目录中的 Pacifico-Regular-all.ttf 是全部的字体文件。
2. （三 - 3中）16a4cnOopswWcdeirstvyHSW 这一段要保留的字体要全部包含你网站中需要修改的字体。
例如：首页显示为6a4，则上方需要包含。反之则不需要包含在内。
3.若不想使用字蛛请直接将 Pacifico-Regular-all.ttf 重命名为 Pacifico-Regular.ttf 即可

**Comment by ZipCz** [comment]
一、在 控制台 安装字蛛（font-spider）（需要安装nodejs）
npm install font-spider -g

二、新建文件
在你的电脑中新建一个文件夹，在文件夹中新建两个文件第一个1.html，第二个font.css。
（一）新建1.html开始
<html>
<head>
  <link rel="stylesheet" href="font.css">
</head>
<body>
  
  <p class="ttf">16a4cnOopswWcdeirstvyHSW</p>
</body>
</html>
新建1.html结束


（二）新建 font.css 开始
@font-face {
  font-family: 'sf-pro-text_regular';
  /* src引入需要精简的ttf字体文件 */
  src: url('./Pacifico-Regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
body {
  font-family: "sf-pro-text_regular";
}
.ttf {
  font-family: 'sf-pro-text_regular';
}
新建 font.css 结束

三、修改文件内容
  1. 修改 src 引入需要精简的ttf字体文件名
 例：src: url('./Pacifico-Regular.ttf') format('truetype');

  2.直接将Pacifico-Regular.ttf放入根目录即可

  3.修改1.html 中要保留的文字
  <p class="ttf">16a4cnOopswWcdeirstvyHSW（这里就是需要保留的文字）</p>

四、在控制台 执行字蛛
font-spider 1.html

五、其他说明
特别注意：根目录 .font-spider 为原始备份文件
1. imsyy主页项目，目录中的 Pacifico-Regular-all.ttf 是全部的字体文件。
2. （三 - 3中）16a4cnOopswWcdeirstvyHSW 这一段要保留的字体要全部包含你网站中需要修改的字体。
例如：首页显示为6a4，则上方需要包含。反之则不需要包含在内。
3.若不想使用字蛛请直接将 Pacifico-Regular-all.ttf 重命名为 Pacifico-Regular.ttf 即可
