### ISSUE TITLE
编辑env文件无用

### ISSUE THREAD

**Issue by W0ngSelf** [imsyy/home#185]
### 站点链接

wongself.fun

### 问题描述

我想更改网站备案和其他信息，env文件无论怎么改都不生效...

**Comment by imsyy** [comment]
我这本地测试没有问题，你看下是不是有缓存

**Comment by jichun29** [comment]
我也是 改完  就标签那里改了 其他都没改动  www.jichun29.cn

**Comment by imsyy** [comment]
改完后需要重新进行部署

**Comment by W0ngSelf** [comment]
> 改完后需要重新进行部署

如何重新部署？这是一个问题

**Comment by imsyy** [comment]
> > 改完后需要重新进行部署
> 
> 如何重新部署？这是一个问题

？

**Comment by imsyy** [comment]
> > 改完后需要重新进行部署
> 
> 如何重新部署？这是一个问题

再运行一次 `pnpm build`

**Comment by W0ngSelf** [comment]
> 

这个命令输入完了之后
root@VM-4-12-ubuntu:/www/wwwroot/home# pnpm build
Command 'pnpm' not found, did you mean:
  command 'npm' from deb npm (8.5.1~ds-1)
Try: apt install <deb name>
