### ISSUE TITLE
可否在前台的天气模块加入手动切换位置的选项？

### ISSUE THREAD

**Issue by ikenliao** [imsyy/home#19]
如题，有时候定位会不准，希望可以直接在前台更换为当前所在地

**Comment by imsyy** [comment]
https://github.com/imsyy/home/blob/ed11a572c92300ed148572149e3be807d250179e/js/main.js#L147
感觉需要手动设置所在地有点不方便 😂，如果想更改的话，可将 [此处](https://github.com/imsyy/home/blob/ed11a572c92300ed148572149e3be807d250179e/js/main.js#L147) 的变量更改为指定城市

**Comment by Aewait** [comment]
> 如题，有时候定位会不准，希望可以直接在前台更换为当前所在地

同，感觉定位非常不准
