### ISSUE TITLE
页脚链接问题

### ISSUE THREAD

**Issue by JERRY-SYSTEM** [imsyy/home#197]
### 站点链接

所有站点均有出现，包括演示站

### 问题描述

页脚Copyright中href指向的链接似乎是`.env`里定义的链接，但是如果`.env`里写`https://`开头的链接，LOGO右侧内容也会带上`https://`，如果不写，页脚href里会指向`https://www.imsyy.top/imsyy.top`。

**Comment by imsyy** [comment]
请修改 env 文件中的环境变量，不要修改 package.json 文件

**Comment by JERRY-SYSTEM** [comment]
> 请修改 env 文件中的环境变量，不要修改 package.json 文件

对不起，我问题描述有误，我确实是改`.env`出现BUG的，而且你的演示站也出现了这个问题，我提issue时不小心写错了，现在已经更正，非常抱歉。

**Comment by imsyy** [comment]
抱歉，确实是疏忽了
