### ISSUE TITLE
没找到控制音乐的配置，不想加载音乐，不在 .env 中填写音乐配置控制台会报错

### ISSUE THREAD

**Issue by yeyulemon** [imsyy/home#209]
### 站点链接

https://yeyulemon.top

**Comment by first19326** [comment]
**.env** 环境变量里面应该有默认的配置，如果控制台报错，有可能是 **接口无法访问**。如果不想加载音乐，将 **Player.vue** 文件中 `onMounted` 中的内容 **注释掉** 即可。目前（**version 4.1.2**）还没有可以控制是否加载音乐的配置。

**Comment by imsyy** [comment]
已添加关闭的方法，将 `VITE_SONG_ID` 设为空即可

**Comment by yeyulemon** [comment]
> **.env** 环境变量里面应该有默认的配置，如果控制台报错，有可能是 **接口无法访问**。如果不想加载音乐，将 **Player.vue** 文件中 `onMounted` 中的内容 **注释掉** 即可。目前（**version 4.1.2**）还没有可以控制是否加载音乐的配置。

可以了，谢谢

**Comment by yeyulemon** [comment]
> 已添加关闭的方法，将 `VITE_SONG_ID` 设为空即可

这种还是会报错，大佬后面版本可以优化一下吗 -_-

**Comment by imsyy** [comment]
> > 已添加关闭的方法，将 `VITE_SONG_ID` 设为空即可
> 
> 这种还是会报错，大佬后面版本可以优化一下吗 -_-

拉取下 `dev` 分支的最新版本
