### ISSUE TITLE
可以直接发布静态资源吗？

### ISSUE THREAD

**Issue by ACZSHOP** [imsyy/home#220]
### 问题描述

换了好几个设备都完全部署不了环境，总是有问题，如果能直接发布静态资源直接就可以用了

**Comment by imsyy** [comment]
现在已经添加了自动部署，可以参考 [说明文档](https://github.com/imsyy/home?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2) 进行操作

**Comment by ACZSHOP** [comment]
> 现在已经添加了自动部署，可以参考 [说明文档](https://github.com/imsyy/home?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2) 进行操作

我的意思是直接发布已经搭建好的资源（下载-上传源码-打开网站），然后我直接在PHP环境里面使用（我在3.6版本也是php环境使用），不需要额外部署.
就像这个链接的程序一样，https://github.com/lizhipay/acg-faka

**Comment by imsyy** [comment]
> > 现在已经添加了自动部署，可以参考 [说明文档](https://github.com/imsyy/home?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2) 进行操作
> 
> 我的意思是直接发布已经搭建好的资源（下载-上传源码-打开网站），然后我直接在PHP环境里面使用（我在3.6版本也是php环境使用），不需要额外部署.
> 就像这个链接的程序一样，https://github.com/lizhipay/acg-faka
> 

我说的就是下载构建好的文件，麻烦看下说明文档
