### ISSUE TITLE
处理weatherData.adCode对象时与教书先生API返回的json对象不符

### ISSUE THREAD

**Issue by L1bws** [imsyy/home#224]
### 站点链接

localhost

### 问题描述

weatherData.adCode里的两个对象与教书先生API返回的json数据中的对象名不符，导致了天气获取失败的报错，但是weatherData.weather是相符的，只不过好像只是因为没获取到城市，所以显示了天气获取失败？

### 补充信息

失败：
![image](https://github.com/imsyy/home/assets/51532767/beb942f4-a0ff-427f-b5cf-d6c8c583f2af)

API返回与代码修复：
![image](https://github.com/imsyy/home/assets/51532767/d0880428-3db4-4ba7-8cd2-fc7df926fbf1)
![image](https://github.com/imsyy/home/assets/51532767/b65320e7-f5e4-4f6d-b05c-fab3eb17753b)

修复后：
![image](https://github.com/imsyy/home/assets/51532767/b99502f5-3f6c-4453-a6de-8f631e6e528a)

_貌似教书先生的API直接是通过IP判断城市然后返回对应天气的，感觉可以删掉对weatherData.adCode.adcode的赋值（或者留着，日后可能会加？）_

**Comment by imsyy** [comment]
已修复，当初是正确的，看来是教书先生 API 接口返回的数据变动了
