### ISSUE TITLE
宝塔部署问题， 根据#104部署完成还是不行，3000端口未监听

### ISSUE THREAD

**Issue by loohalh** [imsyy/home#240]
### 问题描述

#在104教程基础上部署完成，过程均未报错，但3000端口未监听，且无法访问

### 补充信息

服务器版本： CentOS Stream release 8，配置2C，2G，内存剩余1.5G左右
node: v16.20.2
yarn: 1.22.21
npm: 8.19.4
源码版本： dev分支最新版，master代码也不行
域名： http，未部署ssl证书
vscode和服务器上均能使用npm dev 
服务器上使用：yarn dev 也能成功

完全按照104教程, 建站目录为/www/wwwroot/home/dist 不行

尝试不在/www/wwwroot/下clone，打包后把dict文件夹内容整体复制到网站根目录下了，其他静态网站也是按照这个方法部署，都没有问题
另外用yarn serve的时候报错，其他项目能跑起来，应该不是yarn的问题，error Command "serve" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<img width="992" alt="image" src="https://github.com/imsyy/home/assets/16890588/3d706de8-fac6-4c97-b946-1a9ccaf5fd60">

3000端口空闲
<img width="1290" alt="image" src="https://github.com/imsyy/home/assets/16890588/74f84567-f3d2-4db3-9b68-7b2cd94263c9">

网站创建：
<img width="639" alt="image" src="https://github.com/imsyy/home/assets/16890588/592e7a49-91de-4ceb-be54-fd79cc22ef2e">

**Comment by shenyunuoyan** [comment]
先打包打包完后设置目录在dist试试

**Comment by loohalh** [comment]
> 先打包打包完后设置目录在dist试试
试过也不行

**Comment by shenyunuoyan** [comment]
在宝塔部署的网站不是默认80端口，然后访问后宝塔根据配置分配吗，然后你看看你域名有没有解析

**Comment by loohalh** [comment]
> 在宝塔部署的网站不是默认80端口，然后访问后宝塔根据配置分配吗，然后你看看你域名有没有解析

解析了，不是配置的3000端口了，到80端口了

**Comment by loohalh** [comment]
部署到80端口了 不是3000端口

**Comment by loohalh** [comment]
部署到80端口了 不是3000端口

**Comment by shenyunuoyan** [comment]
现在可以了是吧

**Comment by loohalh** [comment]
> 现在可以了是吧

嗯 谢谢
