### ISSUE TITLE
关于天气（定位）API

### ISSUE THREAD

**Issue by wcbing** [imsyy/home#25]
我有自己的和风key，但是天气经常提示次数超限，应该是ROLL的定位API超出。

现在我用一个背景透明的“简约插件”替换，看着也还算协调。希望考虑用这个代替，也可以少申请一个API。
问题一是不居中，二是弹出卡片被遮挡，但都不难解决
![图片](https://user-images.githubusercontent.com/63220331/192991049-0dde56ad-7a56-43d3-bae9-b7083823431c.png)

**Comment by imsyy** [comment]
将来有空了在考虑重构一下，这些都会改进的 😂
