### ISSUE TITLE
能否像homarr一样给标签加上一个简单的状态显示

### ISSUE THREAD

**Issue by aonoa** [imsyy/home#254]
### Description of the Issue

![image](https://github.com/imsyy/home/assets/32682251/4015b1f3-d1c7-4707-b929-4428b6312639)
如图，右下角那里加一个类似的状态检测
![image](https://github.com/imsyy/home/assets/32682251/7b0a2e1d-9c41-445c-ab0a-41fbd818003f)

**Comment by imsyy** [comment]
如果只是想要单纯的样式，可以自行添加，本项目不是网站监测项目
