### ISSUE TITLE
壁纸相对于老版本有拉伸，会导致画质变糊

### ISSUE THREAD

**Issue by Jerry-FaGe** [imsyy/home#259]
### 站点链接

http://jerryfage.top

### 补充信息

好像自从某次 commit 之后默认壁纸就会被拉伸导致看起来比以前糊很多，具体可以看下视频。是因为把 webp 换成 jpg 了么。

还有之前切换壁纸是实时更改的，现在变成必须刷新页面才能更改，不是很理解为什么要这么做。

https://github.com/imsyy/home/assets/40235071/603d2a6d-3def-4df3-9dc6-318894bd42ed

**Comment by imsyy** [comment]
1. 换成 jpg 是因为有人说他的浏览器不支持显示 webp，可自行更换
2. 图片模糊是因为我这访问量太大，不得已压缩的，可以自行更换高清的
3. 刷新生效这个问题倒是可以优化一下，但是最近比较忙，无心维护，等过段时间倒是可以优化下

**Comment by Jerry-FaGe** [comment]
感觉不是图片本身质量的问题，视频中新版页面的壁纸对比老版页面明显是被拉伸了，幅度还不小，已经到了出现锯齿的程度。
我在本地测试了新代码搭建的网页跟视频里的效果是一样的，如果您的壁纸没有改过宽高比的话，应该是代码里某处的拉伸配置出了问题吧（猜的）。

**Comment by imsyy** [comment]
> 感觉不是图片本身质量的问题，视频中新版页面的壁纸对比老版页面明显是被拉伸了，幅度还不小，已经到了出现锯齿的程度。 我在本地测试了新代码搭建的网页跟视频里的效果是一样的，如果您的壁纸没有改过宽高比的话，应该是代码里某处的拉伸配置出了问题吧（猜的）。

不是宽高比，是由原版的 `transform: scale(1)` 改为了 `transform: scale(1.2)`，但是我忘记了为什么改了这个 😂，一直用的第三方壁纸，没发现（其实还是图片太模糊了）

**Comment by Jerry-FaGe** [comment]
![image](https://github.com/imsyy/home/assets/40235071/5524e05e-3115-49e6-b9cb-cdd09e0143d9)

原来是这样😮感谢解答，看记录是把 transform 给去掉了，请问新增的属性中哪个可以控制缩放呢，我想把它改回来，F12 里试了半天都没有效果

**Comment by imsyy** [comment]
在 https://github.com/imsyy/home/blob/c068f676d1b6fcd535ac2d91a34ef6b4343885bc/src/style/style.scss#L164 这里
把 to 中的动画参数改一下就行了

**Comment by Jerry-FaGe** [comment]
> 在
> 
> https://github.com/imsyy/home/blob/c068f676d1b6fcd535ac2d91a34ef6b4343885bc/src/style/style.scss#L164
> 
> 这里
> 把 to 中的动画参数改一下就行了

感谢大佬指点🙏这下舒服了😄

**Comment by imsyy** [comment]
> > 在
> > https://github.com/imsyy/home/blob/c068f676d1b6fcd535ac2d91a34ef6b4343885bc/src/style/style.scss#L164
> > 
> > 这里
> > 把 to 中的动画参数改一下就行了
> 
> 感谢大佬指点🙏这下舒服了😄

ok，好了就行，我随后的版本修复一下
