### ISSUE TITLE
大佬，为什么生成完的dist，打开里面的html是空白？

### ISSUE THREAD

**Issue by Kanon1982** [imsyy/home#280]
### 站点链接

https://www.fan2333.top/

### 问题描述

大佬，为什么生成完的dist，打开里面的html是空白？

### 补充信息

大佬，为什么生成完的dist，打开里面的html是空白？
![Snipaste_2024-04-17_14-56-39](https://github.com/imsyy/home/assets/47709340/88d1fef8-5cff-4af1-86e2-195ca22b17ff)

**Comment by Kanon1982** [comment]
> ### 站点链接
> https://www.fan2333.top/
> 
> ### 问题描述
> 大佬，为什么生成完的dist，打开里面的html是空白？
> 
> ### 补充信息
> 大佬，为什么生成完的dist，打开里面的html是空白？ ![Snipaste_2024-04-17_14-56-39](https://private-user-images.githubusercontent.com/47709340/323111934-88d1fef8-5cff-4af1-86e2-195ca22b17ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzczMTYsIm5iZiI6MTcxMzMzNzAxNiwicGF0aCI6Ii80NzcwOTM0MC8zMjMxMTE5MzQtODhkMWZlZjgtNWNmZi00YWYxLTg2ZTItMTk1Y2EyMmIxN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2NTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNTE3ZGFmNWUzN2QzOTBhYjQyZGVlZmExNWQ5ZmE1YTQwNmIzOWRiYzgxNmRkZWQ2NGExOWYyMzE5ZTU1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKZBfzhNFeHG6Sc_v4avOFalZ31ifb6ANacXIpbXkc8)

本地打开生成的html，显示为空。。。

**Comment by imsyy** [comment]
#92

**Comment by Kanon1982** [comment]
谢谢大佬，成功了
