### ISSUE TITLE
二级目录访问需要强制刷新才能访问。

### ISSUE THREAD

**Issue by tinyhugh** [imsyy/home#289]
### 站点链接

520xm.top

### 补充信息

使用nginx，根目录设置为该项目，其他后端服务为二级目录，不管直接在浏览器访问二级目录还是在网站列表通过点击访问二级目录都不能正常跳转到后端服务，必须使用shift+F5强制刷新才能正常访问。

**Comment by ghost** [comment]
请问有解决方法了吗

**Comment by QWQLwToo** [comment]
没有吧，我看就dev频道更新了，master没更

**Comment by iamckun** [comment]
@imsyy 看看这个问题吧帮大忙啊

**Comment by iamckun** [comment]
把vite.config.js 里面的这个 删了VitePWA，我现在可以访问二级目录了，就是不知道全部删了会有什么影响，是不是可以只改某些参数注释某些参数达到目录，大家一起看看

**Comment by cooker** [comment]
遇到同样的问题了
第一次访问 https://hapgpt.com/movie.html
第二次访问 https://hapgpt.com
会导致二级页面无法访问

**Comment by first19326** [comment]
因为这个项目只是一个简单的单页面应用的 Vue 项目，没有做页面路由，所以使用二级目录这种的无法跳转，建议使用二级域名，这样不会有这种问题。

**Comment by musnows** [comment]
nginx要把二级目录配置到根目录的反代前面，就不会这样跳转了
