### ISSUE TITLE
请求添加自定义背景

### ISSUE THREAD

**Issue by ZH4201** [imsyy/home#322]
### 问题描述

网页背景模糊，更换其他背景后打不开网页

**Comment by NanoRocky** [comment]
可以添加自定义背景的喔，请注意文件名和文件格式。文件名必须是“background+数字”，全部图片格式必须一致。
壁纸相关的设置在“src/components/Background.vue” 。
如果觉得默认格式图片比较模糊，可以在“//更换壁纸链接”处，修改 ${bgRandom} 后面的文件后缀。

`// 更换壁纸链接
const changeBg = (type) => {
  if (type == 0) {
    bgUrl.value = `images/background${bgRandom}.**webp**`;
  } else if (type == 1) {`

还有“// 图片显示失败”处，同样修改 ${bgRandom} 后面的文件后缀。

`bgUrl.value = `images/background${bgRandom}**.webp**`;`

增加或减少导致图片数量变化，需要修改“`// 壁纸随机数”。

`// 壁纸随机数
// 请依据文件夹内的图片个数修改 Math.random() 后面的第一个数字
const bgRandom = Math.floor(Math.random() * 37 + 1);`

以下是效果参考。
[https://nanorocky.top](url)

**Comment by ZH4201** [comment]
感谢大佬，已经解决了₍˄·͈༝·͈˄*₎◞ ̑̑



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月17日 18:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [imsyy/home] 请求添加自定义背景 (Issue #322) |

可以添加自定义背景的喔，请注意文件名和文件格式。文件名必须是“background+数字”，全部图片格式必须一致。
壁纸相关的设置在“src/components/Background.vue” 。
如果觉得默认格式图片比较模糊，可以在“//更换壁纸链接”处，修改 ${bgRandom} 后面的文件后缀。

// 更换壁纸链接 const changeBg = (type) => { if (type == 0) { bgUrl.value = images/background${bgRandom}.webp; } else if (type == 1) {

还有“// 图片显示失败”处，同样修改 ${bgRandom} 后面的文件后缀。

bgUrl.value = images/background${bgRandom}.webp;

增加或减少导致图片数量变化，需要修改“`// 壁纸随机数”。

// 壁纸随机数 // 请依据文件夹内的图片个数修改 Math.random() 后面的第一个数字 const bgRandom = Math.floor(Math.random() * **37** + 1);

以下是效果参考。
https://nanorocky.top

**Comment by CsVeryLoveXieWenLi** [comment]
**如果真正解决了，请关闭issues。**
