### ISSUE TITLE
有什么办法可以加上逐字歌词吗？

### ISSUE THREAD

**Issue by NanoRocky** [imsyy/home#323]
### 问题描述

大佬好，问问有什么办法可以加上逐字歌词吗？不过 MetingApi 貌似不能解析逐字歌词，我也不会改...
在必应翻来翻去看到那个 SPlayer 项目有逐字歌词功能，想问问是如何实现的...（）

**Comment by CsVeryLoveXieWenLi** [comment]
**需要歌词支持吧，毕竟你显示的话要对时间轴的？**

**Comment by NanoRocky** [comment]
知道哇，所以才问有没有什么办法解析到逐字歌词嘛

**Comment by imsyy** [comment]
> 知道哇，所以才问有没有什么办法解析到逐字歌词嘛

有一说一，我也在找除了 NeteaseCloudMusicApi 之外能获取歌词的 api

**Comment by CsVeryLoveXieWenLi** [comment]
> 知道哇，所以才问有没有什么办法解析到逐字歌词嘛

**估计需要逆向非WEB协议？不对，应该不需要，你可以搜索逐字歌词相关的实现，我不太了解。为何我说不用，因为有些第三方网易云，貌似并没有逆向非WEB协议，但是有逐字歌词，你可以参考一下。**

**Comment by CsVeryLoveXieWenLi** [comment]
> > 知道哇，所以才问有没有什么办法解析到逐字歌词嘛
> 
> 有一说一，我也在找除了 NeteaseCloudMusicApi 之外能获取歌词的 api

**[HyPlayer](https://github.com/HyPlayer/HyPlayer) 你可以看看这个实现，这是我之前找到的，貌似采用WEB协议，但是设置中的逐字歌词为实验性。**

**并且，值得一提的是，此项目引用了NeteaseCloudMusicApi，并重写为Csharp版本。**

**Comment by CsVeryLoveXieWenLi** [comment]
**经过我的一点搜索，并不是所有歌曲都有逐字歌词，而且也没必要，像纯音乐，是不需要逐字歌词的。**

**目前网易云音乐独有的YRC是逐字歌词，LRC是通用的逐行歌词。详情请参考：[Lyrics4](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/Lyrics.md)**

**Comment by NanoRocky** [comment]
Api 有了，差修改主页了（）
[MetingApi](https://metingapi.nanorocky.top/)
稍微修改了亿下下...带上”&yrc=true“就可以获取到逐字歌词了。[示例](https://metingapi.nanorocky.top/?server=netease&type=lrc&id=1925446593&yrc=true)
等后面成功了再找机会去 MetingApi 那提个 pr 叭（

**Comment by NanoRocky** [comment]
额..还是遇到了些瓶颈...APlayer 负责的太广了，大部分功能都被 APlayer 解决了。我没办法实现当接口返回的是逐字歌词时，让 APlayer 不处理，而扔给新函数...
