### ISSUE TITLE
如何增删链接呢？

### ISSUE THREAD

**Issue by lolo1024** [imsyy/home#336]
### 站点链接

0520.com.cn

### 问题描述

想要添加更多链接应该修改哪里呢？

**Comment by NanoRocky** [comment]
站点设置在 \src\assets\siteLinks.js 内。如需设置图标，在 \src\components\Links.vue 。另外，该议题不属于 BUG 喔，还是不要随意加标签嘟啦！

**Comment by lolo1024** [comment]
抱歉，我不太会弄这个，点着就成BUG了
siteLinks.js 和Links.vue我都修改了，但是并没有增加新的一项，不知道哪里错误，
在 src/assets/siteLinks.json 中我新加
{
  "icon": "Blog",
  "name": "博客",
  "link": "https://blog.imsyy.top/"
},
并没有新增加一项链接呢

**Comment by lolo1024** [comment]
会报错

**Comment by lolo1024** [comment]
解决了
