### ISSUE TITLE
关于音乐播放器

### ISSUE THREAD

**Issue by FengmiQingmei** [imsyy/home#34]
音乐播放器能否加个使用自己账户的cookie去播放音乐？因为自己开了QQ音乐的vip且部分喜欢听的歌都要QQ音乐的vip。T_T !!!

**Comment by imsyy** [comment]
抱歉，目前无法通过该方法播放 QQ 音乐的 vip 歌曲（ MetingJs 不支持且貌似暂时[无法使用](https://github.com/Rain120/qq-music-api/issues/15#issuecomment-1121933374) ）

**Comment by FengmiQingmei** [comment]
你的邮件我已收到。

**Comment by FengmiQingmei** [comment]
今天找到了[这个](https://github.com/jsososo/QQMusicApi)，刚接触代码我不是很懂怎么修改这个接口配置

**Comment by FengmiQingmei** [comment]
你发的那个接口我今天搭建过，但是一直报错，所以找到了且成功在自己服务器上搭建了这个[接口](https://github.com/jsososo/QQMusicApi)，但是我不会改你的代码   T_T!!!

**Comment by imsyy** [comment]
我去瞅瞅 🧐

**Comment by FengmiQingmei** [comment]
你的邮件我已收到。
