### ISSUE TITLE
QQ音乐无法获取vip歌曲播放链接

### ISSUE THREAD

**Issue by hwxlikemi** [imsyy/home#345]
### 站点链接

https://hwxlikemi-home.pages.dev/

### 问题描述

QQ音乐无法获取vip歌曲播放链接(只试了周杰伦)

### 补充信息

![Screenshot_2024-08-20-18-24-49-953_mark via](https://github.com/user-attachments/assets/59ca2cee-ed34-4e09-87fb-6e7ac4f6b2cf)

![Screenshot_2024-08-20-18-30-09-443_mark via](https://github.com/user-attachments/assets/cc6d95a0-fed7-4eb4-9840-685554d1de47)

**Comment by NoSetViolin** [comment]
解决了吗？你怎么解决的
