### ISSUE TITLE
背景图片应该怎么更换？

### ISSUE THREAD

**Issue by HansOffice** [imsyy/home#39]
打扰了，作者大大  

这是我看到的，请我应该怎么做才能为此
![屏幕截图(6)](https://user-images.githubusercontent.com/94523696/210930891-6bb14b37-ac93-4f18-a083-f8c13ed00310.png)
更换背景图片呢？

**Comment by imsyy** [comment]
如果想要更改壁纸链接，可以更改这里
https://github.com/imsyy/home/blob/9da5e5004081768c08dfbb82817a95635d82acb9/js/set.js#L30

**Comment by HansOffice** [comment]
ok，我尝试一下
