### ISSUE TITLE
搭建问题

### ISSUE THREAD

**Issue by kazukokawagawa** [imsyy/home#48]
在尝试搭建vue重构的4.0.0版本时，打开index.html之后出现以下界面
![7DECBF81-70F2-486E-A3A1-56D1FDEAF779](https://user-images.githubusercontent.com/109492503/215256940-aaba39fc-c46c-4c74-b85d-a23d50cd40b8.png)

**Comment by imsyy** [comment]
请在根目录执行

```
yarn install
yarn dev
yarn build
```

**Comment by kazukokawagawa** [comment]
直到2026我回看才知道我自己当时多蠢

**Comment by imsyy** [comment]
可以在 fork 并修改 env 文件后用 vercel 一键部署

**Comment by kazukokawagawa** [comment]
何异味
