### ISSUE TITLE
希望把社交链接添加if判断

### ISSUE THREAD

**Issue by Aewait** [imsyy/home#49]
如题，如果我不需要email、推特、tg，我得去手动注释`\src\components\SocialLinks` 里面的代码

个人认为需要加上判断，如果`.env`中没有对应环境变量，或者环境变量为空，就直接不显示这个图标；

另外，添加新的社交链接不算特别方便，如果能通过env设置 `图标、链接、鼠标点击时显示什么` 就好了。这样就不需要改代码了；修改代码对于没学过前端的人不是很友好（我还是靠照抄改好的）

**Comment by imsyy** [comment]
收到，下个版本会改进的

**Comment by Aewait** [comment]
![image](https://user-images.githubusercontent.com/87506951/215301817-93fb4131-ab5f-4bab-9f8e-89b0054ab4cc.png)
另外，部分字体没办法正常显示，请问这个是啥情况。html里面的链接已经换过了

**Comment by imsyy** [comment]
> ![image](https://user-images.githubusercontent.com/87506951/215301817-93fb4131-ab5f-4bab-9f8e-89b0054ab4cc.png)
> 还有一个问题，部分字体没办法正常显示，请问这个是啥情况？html里面的链接已经换过了
> ```
>   <link rel="stylesheet" href="https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" />
> ```

>主页的 Logo 字体已经过压缩，若用本站 Logo 以外的字母会变回默认字体，这里是 [完整字体](https://file.4everland.app/font/Other/Pacifico-Regular.ttf)

**Comment by Aewait** [comment]
> 

搞定了，谢谢

**Comment by Aewait** [comment]
还有一个问题，如果网站链接大于6个，第三排会和第二排直接贴上😂😂

![9~Z`S)59OTDY7U6[`418{1A.png](https://user-images.githubusercontent.com/87506951/215303677-07aa7b6f-bf6f-4e9e-909f-6ef03de8b22f.png)

**Comment by Aewait** [comment]
另外一个关于代码的问题（我没学前端，所以不太清楚）这里我用了img添加了一个gitee的链接，但是它的边距和其他图标不统一，请问有没有啥办法能控制一下边距？
![](https://img.kookapp.cn/assets/2023-01/os4A3kYSk009l02p.png)

```
      <a
        id="gitee"
        :href="socialLinks.gitee"
        target="_blank"
        @mouseenter="changeTip"
        @mouseleave="leaveTip"
      >
        <img 
          src="/images/icon/gitee.png" height="24"
        />
      </a>
```
