### ISSUE TITLE
卡片透明度的问题

### ISSUE THREAD

**Issue by yuranas** [imsyy/home#54]
我想问下 如果要修改卡片透明度 在哪可以修改，本人菜鸟 希望大佬不要介意我这愚蠢的问题 >.<

**Comment by imsyy** [comment]
https://github.com/imsyy/home/blob/65d24f05d152dd777381d4c4aa5363708ea1f1bc/src/style/style.scss#L62

改变这里面的 `blur(10px)` 值就行了，或者其他地方也有这个值，你找找看
