### ISSUE TITLE
Node Npm Yarn版本

### ISSUE THREAD

**Issue by Tncent** [imsyy/home#65]
太感谢这么高质量的Vue项目了，界面非常好看，但是在我自己编译的时候却出现了问题

npm -v
8.1.2
node -v
v16.13.1

yarn build
yarn run v1.22.19
$ vite build
vite v3.1.8 building for production...                                                     03:29:27
error Command failed with signal "SIGKILL".

**Comment by imsyy** [comment]
我的 node 版本是
npm -v
8.15.0
node -v
v16.16.0

不过一般这个错误是在安装依赖时内存不足，如果是在云服务上安装的话就有可能出现这个错误（我的破服务器就会有这个错误 🤣）
