### ISSUE TITLE
音乐播放器提示加载失败

### ISSUE THREAD

**Issue by xzzxyz** [imsyy/home#74]
大佬 音乐播放器提示加载失败 换了备用api后歌词加载不出来 怎么改呢？

**Comment by imsyy** [comment]
已解决

**Comment by kxhubs** [comment]
> 已解决

这个是怎么解决的 relese里下载 预览还是提示播放器加载失败 更新里不是说吧音乐播放器独立出来了么

**Comment by imsyy** [comment]
> > 已解决
> 
> 这个是怎么解决的 relese里下载 预览还是提示播放器加载失败 更新里不是说吧音乐播放器独立出来了么

从 dev 分支拉取最新更新，relese 里面的还没更新
