### ISSUE TITLE
在yarn dev的过程中报错

### ISSUE THREAD

**Issue by miaowmint** [imsyy/home#80]
把源码git后修改.env然后cd到项目目录下执行yarn install正常，执行yarn dev时报错

具体报错如图

![image](https://user-images.githubusercontent.com/58991169/217523747-518726e3-ebb1-479f-baf8-bc27d73aeb71.png)

yarn run v1.22.19
$ vite
  VITE v3.1.8  ready in 1055 ms

  ➜  Local:   http://127.0.0.1:3000/                                                                                                                                                                     
  ➜  Network: use --host to expose                                                                                                                                                                       
/root/home/node_modules/esbuild/lib/main.js:1113
        return callback(new Error(error), null);
                                 ^

Error: The service was stopped: write EPIPE
    at /root/home/node_modules/esbuild/lib/main.js:1113:25
    at Object.responseCallbacks.<computed> (/root/home/node_modules/esbuild/lib/main.js:671:9)
    at afterClose (/root/home/node_modules/esbuild/lib/main.js:661:28)
    at /root/home/node_modules/esbuild/lib/main.js:2050:11
    at onwriteError (node:internal/streams/writable:417:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

nodejs版本为v16.19.0
npm版本为9.4.2
yarn版本为1.22.19
![image](https://user-images.githubusercontent.com/58991169/217524132-4c353065-223b-4ce3-8805-49ccbe6581d3.png)

**Comment by xiqoqi** [comment]
后续运行yarn build报错如下，服务器系统为centos7.9

![image](https://user-images.githubusercontent.com/58991169/217525173-785e41d6-4c29-43cd-b7df-460c089df0da.png)

**Comment by imsyy** [comment]
这个可能是服务器内存过低，可以在实体机构建试试
