### ISSUE TITLE
logo 首字母为小写 j 时会被裁切，大写正常

### ISSUE THREAD

**Issue by Jerry-FaGe** [imsyy/home#82]
我的网站是以小写字母 `j` 打头的，调试的时候发现前面一点会被裁切，如图：

![首字母小j](https://user-images.githubusercontent.com/40235071/218254484-d2ec2459-bf31-46a2-b7f6-a0aa1088c704.png)

换成大写 `J` 就没有问题

![首字母大J](https://user-images.githubusercontent.com/40235071/218254529-92abefbb-0fdb-4957-98e5-1789ef8fc773.png)

但是换成大写的会让后面长出引言框一大截，看着还是挺不舒服的

![域名过长](https://user-images.githubusercontent.com/40235071/218254881-dc16673e-7abe-442a-aa2b-69a3e2a025fe.png)

不知道如果域名比较长的情况下有什么方法可以调优这个样式

**Comment by imsyy** [comment]
正在想办法解决这个问题 😂

**Comment by first19326** [comment]
@Jerry-FaGe 这个问题，我可以给你个解决方案，首页的话应该算完美，但是其他页面不是特别完美，首页这个地方的容器有个 margin-left 的样式，你调整为 padding-left 就可以解决这个问题。归根究底这个问题是由于字体样式造成的，因为这个字体会超出容器限制。

**Comment by Jerry-FaGe** [comment]
> @Jerry-FaGe 这个问题，我可以给你个解决方案，首页的话应该算完美，但是其他页面不是特别完美，首页这个地方的容器有个 margin-left 的样式，你调整为 padding-left 就可以解决这个问题。归根究底这个问题是由于字体样式造成的，因为这个字体会超出容器限制。

感谢你提供的思路，我调整出了适合我的样式，以下放出我的调整以供参考：

- 先调首页 [src/components/Message/index.vue](/imsyy/home/blob/d87d467dc7a00105577110d92535cb66f933539a/src/components/Message/index.vue#L92-L101)

```DIFF CSS
.name {
  width: 100%;
  height: 142px;
- margin-left: 12px;
+ // margin-left: 12px;
  transform: translateY(-15px);
  font-family: "Pacifico-Regular";

  .bg {
    font-size: 5rem;
+   padding-left: 1.2rem;
  }
```

- 至于其他页面有这个样式的，目前就找到了设置页面 [src/views/MoreSet/index.vue](/imsyy/home/blob/d87d467dc7a00105577110d92535cb66f933539a/src/views/MoreSet/index.vue#L157-L159)

```DIFF CSS
.bg {
  font-size: 5rem;
+ padding-left: 1.2rem;
}
```

只测试了小写字母 `j` 的表现，其他字母因为有字体压缩就懒得测了(
本人不咋懂前端，如果这样写兼容性会更好的话希望 @imsyy 可以采纳或者我提个 pr

现在就剩下过长域名会超出引言框这里的样式不知道该怎么调整了

![image](https://github.com/imsyy/home/assets/40235071/607c5a79-316a-4954-b541-ef739354e5ae)
