### ISSUE TITLE
git拉去源码 预览为什么只显示一个空白的加载中

### ISSUE THREAD

**Issue by kxhubs** [imsyy/home#83]
![1676290666857](https://user-images.githubusercontent.com/20880604/218455600-dfcc469d-37f0-4ab9-aa58-664bf6ff092b.jpg)

**Comment by imsyy** [comment]
本地最好使用 localhost 访问，强制 https 我去掉了，现在应该可以访问了

**Comment by kxhubs** [comment]
> 本地最好使用 localhost 访问，强制 https 我去掉了，现在应该可以访问了

我用localhos访问也是一样的效果，编译完成之后还是这样的效果，我用release发布下的那个版本预览和编译都正常，git拉下来的就都是这样的空白页面写个加载中

**Comment by imsyy** [comment]
> > 本地最好使用 localhost 访问，强制 https 我去掉了，现在应该可以访问了
> 
> 我用localhos访问也是一样的效果，编译完成之后还是这样的效果，我用release发布下的那个版本预览和编译都正常，git拉下来的就都是这样的空白页面写个加载中

那就先用 release 里的吧

**Comment by kxhubs** [comment]
> 

我用最新的release预览也是一样不正常的，用上一个版本是没问题的  服务器是debian11 node是1814 npm是9.3.1的

**Comment by kxhubs** [comment]
> > > 本地最好使用 localhost 访问，强制 https 我去掉了，现在应该可以访问了
> > 
> > 
> > 我用localhos访问也是一样的效果，编译完成之后还是这样的效果，我用release发布下的那个版本预览和编译都正常，git拉下来的就都是这样的空白页面写个加载中
> 
> 那就先用 release 里的吧

没问题了 是依赖没有安装全  字体这个怎么搞 css也已经改了 字体还是不生效

**Comment by imsyy** [comment]
哪里的字体

**Comment by kxhubs** [comment]
> 哪里的字体

就是域名那个字体
![1676357185480](https://user-images.githubusercontent.com/20880604/218660063-422f7bfd-c728-42a0-9ceb-0cb79092662c.jpg)

**Comment by imsyy** [comment]
> > 哪里的字体
> 
> 就是域名那个字体 ![1676357185480](https://user-images.githubusercontent.com/20880604/218660063-422f7bfd-c728-42a0-9ceb-0cb79092662c.jpg)

![image](https://user-images.githubusercontent.com/42232682/218661229-4a4fb7aa-4765-4dcf-b3bb-8717cf4bc57a.png)
